### PR TITLE
Add a function to exit mario if the use key is pressed

### PR DESCRIPTION
**Pull request by ecumber**
As of now it's not possible to exit mario unless you have a kill bind, so I added a simple check if the use key is pressed so you can exit mario with a keypress.

### CODE REVIEW

**Comment by somario360** [comment]
Undo allows you to exit mario mode

**Comment by ecumber** [comment]
> Undo allows you to exit mario mode

True, however there may be cases (such as if you spawn objects as mario) where a dedicated exit button is used because you would have to undo a lot of stuff before you can exit mario mode.

**Comment by GreenSwede** [comment]
I would prefer if the use key is kept intact, simply because I use the use key in HL1/HL2 maps to use buttons/doors etc. Best option would be to have this be optional, or alternatively have a dedicated console command that you can bind to any button that you want.

**Comment by ckosmic** [comment]
How about the reload key?

**Comment by ecumber** [comment]
I have changed the key to be reload, hopefully should work

**Pull request merged**
